### ISSUE TITLE
Doesn't handle nested folders

### ISSUE THREAD

**Issue by nicktimakondu** [SC5/serverless-mocha-plugin#7]
When i try to create a function or test where the function is inside a nested folder, it fails to create the directories in the tree up to the folder under test.

```
sls function create functions/sample/sub/folder
Serverless: Please, select a runtime for this new Function
    nodejs
  > nodejs4.3
    python2.7
Serverless: For this new Function, would you like to create an Endpoint, Event, or just the Function?
    Create Endpoint
    Create Event
  > Just the Function...
Serverless: Successfully created function: "functions/sample/sub/folder"
/usr/local/lib/node_modules/serverless/node_modules/bluebird/js/release/async.js:49
        fn = function () { throw arg; };
                           ^

Error: Creating file test/functions_sample/sub/folder.js failed: Error: ENOENT: no such file or directory, open 'test/functions_sample/sub/folder.js'
    at /Users/nick/Development/sample_project/node_modules/serverless-mocha-plugin/index.js:173:34
    at fs.js:1197:21
    at OpenReq.Req.done (/Users/nick/Development/sample_project/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/Users/nick/Development/sample_project/node_modules/graceful-fs/graceful-fs.js:63:22)
    at FSReqWrap.oncomplete (fs.js:83:15)
From previous event:
    at Serverless._execute (/usr/local/lib/node_modules/serverless/lib/Serverless.js:200:19)
    at Serverless.actions.(anonymous function) (/usr/local/lib/node_modules/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/usr/local/lib/node_modules/serverless/lib/Serverless.js:398:38)
    at /usr/local/lib/node_modules/serverless/bin/serverless:19:16
    at processImmediate [as _immediateCallback] (timers.js:384:17)
From previous event:
    at Object.<anonymous> (/usr/local/lib/node_modules/serverless/bin/serverless:18:4)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)
    at node.js:977:3
```

**Comment by calam1** [comment]
I also run into the same issue

```
  serverless:lib.utils.index Writing file: /Users/christopherlam/git/development/serverless/example-serverless/restApi/mochaexample/exampleFunction1/event.json... +0ms
Serverless: Successfully created function: "restApi/mochaexample/exampleFunction1"
/Users/christopherlam/git/development/junk/serverless/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^

Error: Creating file test/restApi_mochaexample/exampleFunction1.js failed: Error: ENOENT: no such file or directory, open 'test/restApi_mochaexample/exampleFunction1.js'
    at /Users/christopherlam/git/development/serverless/example-serverless/node_modules/serverless-mocha-plugin/index.js:173:34
    at fs.js:1196:7
    at OpenReq.Req.done (/Users/christopherlam/git/development/serverless/example-serverless/node_modules/mocha/node_modules/graceful-fs/graceful-fs.js:143:5)
    at OpenReq.done (/Users/christopherlam/git/development/serverless/example-serverless/node_modules/mocha/node_modules/graceful-fs/graceful-fs.js:63:22)
    at FSReqWrap.oncomplete (fs.js:82:15)
From previous event:
    at Serverless._execute (/Users/christopherlam/git/development/junk/serverless/lib/Serverless.js:200:19)
    at Serverless.actions.(anonymous function) (/Users/christopherlam/git/development/junk/serverless/lib/Serverless.js:429:20)
    at Serverless.command (/Users/christopherlam/git/development/junk/serverless/lib/Serverless.js:398:38)
    at /Users/christopherlam/git/development/junk/serverless/bin/serverless:19:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Object.<anonymous> (/Users/christopherlam/git/development/junk/serverless/bin/serverless:18:4)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

```

**Comment by rafaljanicki** [comment]
Similar for me:

`λ sls function create functions/users/create
Serverless: Please, select a runtime for this new Function
  > nodejs4.3
    python2.7
    nodejs (v0.10, soon to be deprecated)
Serverless: For this new Function, would you like to create an Endpoint, Event, or just the Function?
  > Create Endpoint
    Create Event
    Just the Function...
Serverless: Successfully created function: "functions/users/create"

λ sls function mocha-create functions/users/create
Unhandled rejection Error: Cannot find module '*PATH*\test\functions_users\create.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at *PATH*\node_modules\serverless-mocha-plugin\node_modules\mocha\lib\mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (*PATH*\node_modules\serverless-mocha-plugin\node_modules\mocha\lib\mocha.js:189:14)
    at Mocha.run (*PATH*\node_modules\serverless-mocha-plugin\node_modules\mocha\lib\mocha.js:422:31)
    at *PATH*\node_modules\serverless-mocha-plugin\index.js:122:21
    at tryCatcher (*PATH*\node_modules\serverless-mocha-plugin\node_modules\bluebird\js\release\util.js:11:23)
    at Promise._settlePromiseFromHandler (*PATH*\node_modules\serverless-mocha-plugin\node_modules\bluebird\js\release\promise.js:489:31)
    at Promise._settlePromise (*PATH*\node_modules\serverless-mocha-plugin\node_modules\bluebird\js\release\promise.js:546:18)
    at Promise._settlePromiseCtx (*PATH*\node_modules\serverless-mocha-plugin\node_modules\bluebird\js\release\promise.js:583:10)
    at Async._drainQueue (*PATH*\node_modules\serverless-mocha-plugin\node_modules\bluebird\js\release\async.js:134:12)
    at Async._drainQueues (*PATH*\node_modules\serverless-mocha-plugin\node_modules\bluebird\js\release\async.js:139:10)
    at Immediate.Async.drainQueues [as _onImmediate] (*PATH*\node_modules\serverless-mocha-plugin\node_modules\bluebird\js\release\async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)`

Note: The plugin was installed AFTER creation of the function, that's why I had to manually create test

**Comment by mpuittinen** [comment]
Since function names need to be unique, I'll probably just strip the folders from the test filename

**Comment by mpuittinen** [comment]
Fixed with serverless-mocha-plugin v0.5.4. mocha-create now uses only the function name for the test file name, not the path. Use only the function name as the parameter for mocha-create (as you do for function run).

**Comment by rafaljanicki** [comment]
Thanks for solving this. Unfortunately, there is still an error - a path generated for const mod is incorrect and has to be fixed manually.

**Comment by mpuittinen** [comment]
This has been fixed with the 0.5.5 version. Thanks for reporting this.
